use strict;
use warnings;
use FindBin qw($Bin);
use File::Temp qw(tempdir);
use Test::More;
require "$Bin/../usr/share/PGenerator/webui.pm";
local $ENV{PGEN_AUTOMATION_DIR} = tempdir(CLEANUP => 1);
PGAutomation::ensure_store();
my $id = PGAutomation::new_id();
my $path = PGAutomation::run_dir($id) . '/run.json';
my $active = {id=>'active',name=>'Active',status=>'running',settings=>{backlight=>80},checkpoints=>[{name=>'greyscale-done',status=>'done'}]};
my $run = {id=>$id,status=>'running',active_item=>0,items=>[$active,{id=>'pending',name=>'Old pending',status=>'queued'}],queue_snapshot=>{items=>[{id=>'original'}]}};
PGAutomation::write_json_atomic($path,$run);
my $response = PGAutomation::decode_json(main::webui_automation_edit_run($id,{first_pending=>1,items=>[{id=>'replacement',name=>'Updated',stages=>{calibration=>0,pre_readings=>1,post_readings=>0}}]}));
is($response->{status},'ok','pending item can be replaced');
my $saved = PGAutomation::read_json_file($path);
is_deeply($saved->{items}[0],$active,'active item and checkpoint evidence remain byte-equivalent');
is($saved->{items}[1]{name},'Updated','pending replacement saved');
is($saved->{items}[1]{stages}{calibration},0,'disabled calibration survives normalization');
is_deeply($saved->{queue_snapshot},$run->{queue_snapshot},'original queue snapshot remains immutable');
$response = PGAutomation::decode_json(main::webui_automation_edit_run($id,{first_pending=>0,items=>[]}));
is($response->{status},'error','truncating the active item is refused');
PGAutomation::with_lock($path,sub {$_[0]{active_item}=1;$_[0]{items}[1]{status}='running';return $_[0]});
$response = PGAutomation::decode_json(main::webui_automation_edit_run($id,{first_pending=>1,items=>[]}));
is($response->{status},'error','stale editor cannot remove an item that became active');
is(scalar(@{PGAutomation::read_json_file($path)->{items}}),2,'stale edit leaves both items intact');
PGAutomation::with_lock($path,sub {$_[0]{status}='completing';return $_[0]});
$response = PGAutomation::decode_json(main::webui_automation_edit_run($id,{first_pending=>2,items=>[{name=>'Too late'}]}));
is($response->{status},'error','cannot append after the runner has claimed completion');
my $artifact_path = PGAutomation::run_dir($id) . '/items/0/pre/greyscale-21.json';
PGAutomation::write_json_atomic($artifact_path,{readings=>[{Y=>100}]});
my $artifact = main::webui_automation_artifact($id,'items/0/pre/greyscale-21.json');
is_deeply(PGAutomation::decode_json($artifact->{data}),{readings=>[{Y=>100}]},'first item (index zero) measurement artifact is readable');
ok(!defined(main::webui_automation_artifact($id,'items/../run.json')),'artifact traversal is refused');
ok(!defined(main::webui_automation_artifact($id,'items//0/pre/greyscale-21.json')),'empty artifact path component is refused');
done_testing();
